version: '2'
services:
    videostore-app:
        image: videostore
        external_links:
            - videostore-postgresql:postgresql
            # Uncomment to have Cassandra working with the gateway
            # - videostore-cassandra:cassandra
            - videostore-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/videostore
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    videostore-postgresql:
        extends:
            file: postgresql.yml
            service: videostore-postgresql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: videostore-cassandra
    videostore-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: videostore-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
