version: '2'
services:
    videostore-postgresql:
        container_name: videostore-postgresql
        image: postgres:9.5.1
        # volumes:
        #     - ~/volumes/jhipster/videostore/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=videostore
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
