videostore-dev-postgresql:
  container_name: videostore-dev-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/videostore/dev-postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=videostore
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
